// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "v1.7.2"

// Copyright ...
var Copyright = "© 2020 - 2023 FloatTech"

// Banner ...
var Banner = "* OneBot + ZeroBot + Golang\n" +
	"* Version " + Version + " - 2023-06-13 15:07:04 +0800 CST\n" +
	"* Copyright " + Copyright + ". All Rights Reserved.\n" +
	"* Project: https://github.com/KomeiDiSanXian/RemiliaBot\n" +
	"* Forked from: https://github.com/FloatTech/ZeroBot-Plugin"
