name: PushLint
on: [ push ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Commit back
        if: ${{ !github.head_ref }}
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "🎨 改进代码样式"

      - name: Create Pull Request
        if: ${{ !github.head_ref }}
        continue-on-error: true
        uses: peter-evans/create-pull-request@v4
